# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_ARCHIVE_LIBLSL_FILE_NAME "liblsl-1.16.1-Win_amd64")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/liblsl-master;C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/build-liblsl-master-Desktop_Qt_6_4_2_MinGW_64_bit-Debug")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "liblsl")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_LIBLSL_DEPENDS "liblsl")
set(CPACK_COMPONENT_LIBLSL_DESCRIPTION "Labstreaminglayer C/C++ library")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_LIBLSL_FILE_NAME "liblsl-1.16.1-Win_amd64.deb")
set(CPACK_DEBIAN_LIBLSL_PACKAGE_NAME "liblsl")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Qt/Tools/CMake_64/share/cmake-3.24/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "liblsl built using CMake")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/liblsl-master;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/liblsl")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "lsl")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "lsl")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/build-liblsl-master-Desktop_Qt_6_4_2_MinGW_64_bit-Debug/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Qt/Tools/CMake_64/share/cmake-3.24/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Labstreaminglayer C/C++ library")
set(CPACK_PACKAGE_FILE_NAME "lsl-1.16.1-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/sccn/liblsl")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "lsl")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "lsl")
set(CPACK_PACKAGE_NAME "lsl")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Labstreaminglayer")
set(CPACK_PACKAGE_VERSION "1.16.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "16")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Qt/Tools/CMake_64/share/cmake-3.24/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "C:/Qt/Tools/CMake_64/share/cmake-3.24/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Qt/Tools/CMake_64/share/cmake-3.24/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/liblsl-master;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/build-liblsl-master-Desktop_Qt_6_4_2_MinGW_64_bit-Debug/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "lsl-1.16.1-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_CMAKE_PACKAGE_REGISTRY "ON")
set(CPACK_WIX_PROPERTY_ARPHELPLINK "https://labstreaminglayer.readthedocs.io/info/getting_started.html#getting-help")
set(CPACK_WIX_SIZEOF_VOID_P "8")
set(CPACK_WIX_UPGRADE_GUID "ee28a351-3b27-4c2b-8b48-259c87d1b1b4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/Fedosov/Documents/projects/Brainstart/Brainstart2/build-liblsl-master-Desktop_Qt_6_4_2_MinGW_64_bit-Debug/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
